# 自定义当前执行文件的名称
name: Service Test
# 整个流程在master分支发生push事件时触发
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行在ubuntu-latest环境的虚拟机中
    steps:
        - uses: actions/checkout@master    #获取master分支
          with:
            ref: master  # 切换到master分支
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1  #使用官方脚本创建java环境
          with:
            java-version: 1.8